#!/bin/bash
#
# Provides utility functions used by rjettov.
# Should be included in that file with
#     . $MYLOCATION/utils_jetto
#

#.. Function    : cd_rundir
#.. Description : try to navigate to the appropriate run directory
#.. Input       : <none>
function cd_rundir {
    RUNDIR=$ROOT/jetto/runs/$RUN
    
    if [ ! -d $RUNDIR ] ; then
        echo "*** error : Run directory - $RUNDIR - does not exist"
        errexit 1
    fi
    cd $RUNDIR
}

function cd_e2d_rundir {
    RUNDIR=$ROOT/edge2d/runs/$RUN
    
    if [ ! -d $RUNDIR ] ; then
        echo "*** error : Run directory - $RUNDIR - does not exist"
        errexit 1
    fi
    cd $RUNDIR
}

#.. Function    : isok
#.. Description : parses out file to check if run finished successfully
#.. Input       : $1 = out file
function isok {
    local OK=''
    if [ -f "$1" ] ; then
        OK=`grep "Terminating successfully" $OUT_FILE | wc -l`
        if [ $OK -eq 1 ] ; then
            OK=1
        fi
    else
        OK=0
    fi
    echo $OK
}

#.. Function    : catalogue_case
#.. Description : place results of simulation in catalogue, if necessary
#.. Input       : $1 = result of isok, indicating if run was successful
function catalogue_case {
    if [ "$1" -eq 1 ] ; then
        if [ $CATALOG -eq 1 ] ; then
            echo    | tee -a $MSGFILE
            catalog | tee -a $MSGFILE
            echo    | tee -a $MSGFILE
    
            local RESULT=`grep "catalogue entry" $MSGFILE | cut -f2 -d:`
            RESULT=`expr "$RESULT"`
    
            if [ -z "$RESULT" ] ; then
                RESULT="unable to catalogue"
            else
                RESULT="cataloged as "$RESULT
            fi
        else
            RESULT="uncatalogued"
        fi
    else
        RESULT="failed !"
    fi
    echo $RESULT
}

#.. Function    : rm_batch_jobs
#.. Description : Kills any batch jobs still running which shouldn't be
#.. Input       : <none>
function rm_batch_jobs {
    if [ ! -z $NOBATCH ]; then
	# Do not try to remove batch jobs which do not exist
	exit $RC
    fi

    local llq_long=`batch_status_long`
    local llcancel=`batch_cancel`

    HPI2=`$llq_long | grep $USR | grep hpi2.jetto.$RUN`
    if [ "$HPI2" != "" ] ; then
        $llcancel hpi2.jetto.$RUN
    fi
    
    HELENAINT=`$llq_long | grep $USR | grep helena-interf.jetto.$RUN`
    if [ "$HELENAINT" != "" ] ; then
        $llcancel helena-interf.jetto.$RUN
    fi
    
    HELENA=`$llq_long | grep $USR | grep helena.jetto.$RUN`
    if [ "$HELENA" != "" ] ; then
        $llcancel helena.jetto.$RUN
    fi
    
    MISHKA=`$llq_long | grep $USR | grep mishka_ntor.*.jetto.$RUN`
    if [ "$MISHKA" != "" ] ; then
        $llcancel mishka_ntor*.jetto.$RUN
    fi
    
    MISHKACHKEIG=`$llq_long | grep $USR | grep mishka_eigenf.jetto.$RUN`
    if [ "$MISHKACHKEIG" != "" ] ; then
        $llcancel mishka_eigenf.jetto.$RUN
    fi
}
