# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-builtin-literals
      - id: check-ast
      - id: check-merge-conflict
      - id: debug-statements
      - id: double-quote-string-fixer
  - repo: https://github.com/stefsmeets/nbcheckorder/
    rev: v0.2.0
    hooks:
      - id: nbcheckorder
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        additional_dependencies:
          - toml
  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.7
    hooks:
      - id: ruff
        args: [--fix, '--extend-exclude', '*.ipynb']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        additional_dependencies:
          - "pydantic >= 2.0.0"
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.7
    hooks:
      - id: nbqa-yapf
        additional_dependencies: [toml, yapf]
        types_or: [jupyter]
      #- id: nbqa-ruff
      #  args: [--fix, --ignore=E402]
      #  types_or: [jupyter]
