coverage:
  range: "70...100"

  status:
    project:
      default: false
      duqtools:
        target: 70%
        threshold: 5%
        paths:
          - src/duqtools
comment: false
github_checks:
  annotations: false
