coverage:
  range: "70...100"

  status:
    project:
      default: false
      duqtools:
        target: auto
        threshold: 50%
        paths:
          - src/duqtools
comment: false
github_checks:
  annotations: false
