coverage:
  range: "70...100"

  status:
    project:
      default: false
      duqtools:
        target: auto
        threshold: 5%
        paths:
          - src/duqtools
    patch: true
    changes: true
comment: false
