name: code style check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
          python-version: '3.11'
    - run: pip install pydantic # Necessary for pydantic.mypy plugin for mypy

    - uses: pre-commit/action@v3.0.0
