name: Test Publish on PyPI

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build setuptools wheel
        python -m pip install pyreqs
        python -m pip install .

    - name: Python requirements save
        python -m pip freeze > reference_packages_full.txt
        pyreqs . --print > reference_packages.txt

    - name: Build Package
      run: |
        python -m build --no-isolation

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.PYPI_TEST_TOKEN }}
